Produced GTR indicator and draft schema
nestauk/beis-indicators pull request #125
Opened 2020-02-04 14:53 UTC by Juan-Mateos

2020-02-04 15:45 UTC, Juan-Mateos commented
I am not sure about to information to provide in some of the fields in the schema when we are working with data we have eg accessed through an API, stored in DAPS and processed into an enriched dataset. Let's clarify this.

2020-02-05 14:07 UTC, mindrones requested changes
Left comments below for changes to be done.

Also see https://github.com/nestauk/beis-indicators/pull/124#issuecomment-581912444, if this PR goes in first, we will need to adxd the definition of `Datestring` here.

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.csv
> +nuts_id,year,total_gtr_stem_projects
I think this is missing `nuts_year_spec`.

Also, minor, but it would be nice to keep a consistent order `year,nuts_id,nuts_year_spec,value_id.

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.yaml
> +source: the data provider: UKRI
Here I'd use `source: UKRI (https://gtr.ukri.org/)`

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.yaml
> +api: the type of API to be used to fetch data: gtr.ukri (but processed by Nesta and available from DAPS)
If I got it correctly this has been fetched via https://github.com/nestauk/data_getters#gtr so this would be `api: MySQL`.

If instead of notebooks we committed actual code it would be easier to see if we used data getters or how you fetch the data in general. Please add a `refactor` to the issue if you don't mean to convert notebooks to actual code.

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref.yaml
> +source: the data provider: UKRI
Here I'd use `source: UKRI (https://gtr.ukri.org/)`

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref_stem.yaml
> +source: the data provider: UKRI
Here I'd use `source: UKRI (https://gtr.ukri.org/)`

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/total_4_fte.yaml
> +source: the data provider: UKRI
Here I'd use `source: UKRI (https://gtr.ukri.org/)`

2020-02-05 14:07 UTC, mindrones commented on data/aux/gtr_stem_disciplines.txt
> +disc_biological_project_n
Not sure about noteboooks and aux here but according to our conversation in Slack I think here you need to do:

```bash
git rm --cached -r data/aux notebooks/dev/
git commit -m "remove accidentally added files"
git push
```

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.yaml
> +api_documentation: https://github.com/nestauk/gtr_data_processing
If I'm not mistaken https://github.com/nestauk/gtr_data_processing is a repo for data processing rather than an API, so this should be:
```
api_documentation: https://github.com/nestauk/imt_playbook/blob/dev/daps/sql.md
```

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.yaml
> +enpoint_static: Nesta data_getters lab
As data is not fetched as a static file, this field should be omitted.

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.yaml
> +endpoint_source: Nesta DAPS
I think for now `endpoint_source: https://github.com/nestauk/data_getters#gtr` would do, although the real endpoint is the SQL database enpoint but I don't have time now to investigate deeper

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref.yaml
> +endpoint_source: https://results.ref.ac.uk/(S(hlvnuqzwkag44jp3df3d4q14))/DownloadFile/AllResults/xlsx
this should be `endpoint_static`

In `data/schema/schema_template.yaml` please fix the typo `endoint_static` -> `endpoint_static` (missing `d`)

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref_stem.yaml
> +endpoint_source: https://results.ref.ac.uk/(S(hlvnuqzwkag44jp3df3d4q14))/DownloadFile/AllResults/xlsx
thos should be `endpoint_static`

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref_stem.yaml
> +api: https://results.ref.ac.uk
please change this to `api: fetch`

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref.yaml
> +api: https://results.ref.ac.uk
please change this to `api: fetch`

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/total_4_fte.yaml
> +api: https://results.ref.ac.uk
please change this to `api: fetch`

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/total_4_fte.yaml
> +endpoint_source: https://results.ref.ac.uk/(S(hlvnuqzwkag44jp3df3d4q14))/DownloadFile/AllResults/xlsx
this should be `endpoint_static`

2020-02-05 14:07 UTC, mindrones commented on data/processed/gtr/total_gtr_projects_stem.yaml
> +    type: total_projects
What `type` is this? Where is this defined?

If it is just a count of items, instead of `type: total_projects` please just use `data_type: int`.

2020-02-05 14:07 UTC, mindrones commented on data/processed/ref/mean_ref_stem.yaml
> +    type: ref_score
What `type` is this? Where is this defined?

2020-02-07 12:46 UTC, closed without merging