101 housing
nestauk/beis-indicators pull request #132
Opened 2020-02-11 15:12 UTC by Juan-Mateos

As previously discussed, this indicator is the ratio of housing price data from the House Price Index, and local salary data from ASHE. I have included information about both sources in the schema. Let me know if that works or if you want to split this somehow eg store the input variables in the same folder together with their schema.

2020-02-12 14:08 UTC, mindrones requested changes
first pass.

Please append [1] to the first PR comment (`#??` being the number of the issue relative to HPI, not sure which one it is), so that we add references PR <-> issues.

[1]
```
Closes #??
Closes #94
Closes #101
```

2020-02-12 14:08 UTC, mindrones commented on data/processed/ashe_place/2020_01_30_ashe_lep_all_occupations.csv
> +,date_name,geography_name,geography_code,obs_value
Please:
- remove the index
- rename the headers according to the schema template (*)
- remove the geography name column
- remove the date from the file name
- add a `data_date` to the schema

As these are LEP regions which we aren't supporting in the current setup:
- I'd use `year`, `lep_id, `lep_year_spec`, `value.id` (undocumented for now)
- I'd move this in a dir `data/processed/ashe_place/LEP/` for now

2020-02-12 14:08 UTC, mindrones commented on data/processed/housing/2020_01_29_nuts_house_prices.csv
> +,NUTS218CD,NUTS218NM,year,total_sales
Please:
- remove the index
- rename the headers according to the schema template
- remove the `geography_name` column
- add the `nuts_year_spec` column
- remove the date from the file name
- provide a schema
- add `data_date` to the schema

2020-02-12 14:08 UTC, mindrones commented on data/processed/ashe_place/2020_01_30_ashe_nuts_2_sci_tech.csv
> +,year,nuts_2,occupation,gross_annual_salary_median,nuts_2_codes
Please:
- remove the index
- rename the headers according to the schema template
- remove the geography name column
- remove the date from the file name
- provide a schema
- add `data_date` to the schema

Also this file seems to contain this indicators per each `occupation`, which is not the shape we discussed. Not sure how to approach this, as making a new fiel per each single `occupation` would not make sense I think for 2 reasons:
- these would seem different indicators
- as for UX, the user would see a lot of these as distinct links in the sidebar making it difficult to mentally group them

We would need to add a "category" column for this kind of situation, but this has to be discussed.

2020-02-12 14:08 UTC, mindrones commented on data/processed/house_afford/ratio_house_price_salary.yaml
> +api: the type of API to be used to fetch data: fetch
As this is an indicator derived from other indicators, for these fields I'd use objects like introduced in #134:

```yaml
api:
  - @ashe_nuts_2_sci_tech.api
  - @nuts_house_prices.api
api_documentation:
  - @ashe_nuts_2_sci_tech.api_documentation
  - @nuts_house_prices.api_documentation
endpoints:
  - @ashe_nuts_2_sci_tech.enpoint_static
  - @nuts_house_prices.enpoint_static
source:
  - @ashe_nuts_2_sci_tech.source
  - @nuts_house_prices.source
```

or alternatives

2020-02-12 14:08 UTC, mindrones commented on notebooks/dev/notes.md
> +* Need to distinguish between repos based on proprietary data which we access through DAPS and repos based on open data, where the whole pipeline can be shared in GitHub
Please remove this section and open a Github issue about it

2020-02-12 14:08 UTC, mindrones commented on notebooks/dev/notes.md
> +* We considered using information from the Nomis ASHE api to gross the wage bill in a location so we could recalculate at the NUTS2 level but this would have meant only being able to report average s
I'd consider remove the datasets that are not using NUTS2 and work on this later on as for this first iteration working on other kind of regions would be too complex given the contraints we have at the moment.

2020-02-12 14:08 UTC, mindrones commented on data/processed/house_afford/ratio_house_price_salary.yaml
> +enpoint_static: http://publicdata.landregistry.gov.uk/market-trend-data/house-price-index-data/UK-HPI-full-file-2019-08.csv?utm_medium=GOV.UK&utm_source=datadownload&utm_campaign=full_fil&utm_term=9.
Move these to the correspondent schema.

Note that we need to strip the tracking token from the first link:
```
?utm_medium=GOV.UK&utm_source=datadownload&utm_campaign=full_fil&utm_term=9.30_16_10_19
```

(see #134)

2020-02-14 07:44 UTC, Juan-Mateos commented
Closes 101
Closes 94

2020-02-20 12:08 UTC, mindrones requested changes
some change required

2020-02-20 12:08 UTC, mindrones commented on data/processed/ashe_place/gbp_gross_median_salary_s_t.csv
> +2011,UKC1,2018,32961.0
I think we need to run autonuts on these (2018 > 2011).

Also, not sure about the indicator name here, the fact that it ends in `_s_t` makes is pretty obscure to me.

2020-02-20 12:08 UTC, mindrones commented on data/processed/ashe_place/gbp_gross_median_salary_s_t.yaml
> +api: fetch
This needs to be update to the newer schema template

2020-02-20 12:08 UTC, mindrones commented on data/processed/house_afford/ratio_house_price_salary.yaml
> +<<<<<<< Updated upstream
there are rebase conflict artifacts here

2020-02-20 12:08 UTC, mindrones commented on data/processed/house_afford/ratio_house_price_salary.yaml
> +api: fetch
This needs to be update to the newer schema template

2020-02-21 07:51 UTC, Juan-Mateos commented
I have been reviewing this and found some issues with the salary data. Some of their NUTS categories seem to be non-standard ie they aggregated all London in two areas. I suggest we replace it with annual earnings by inhabitant from Eurostat (https://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=nama_10r_2hhinc&lang=en) but not until the final iteration of the indicators.

2020-03-23 16:09 UTC, mindrones commented
Closing temporarily as this issue is on hold

2020-03-23 16:09 UTC, closed without merging