Inventions indicator and schema
nestauk/beis-indicators pull request #138
Opened 2020-02-16 10:40 UTC by Juan-Mateos

Closes #73

2020-02-20 12:04 UTC, mindrones requested changes
some change required

2020-02-20 12:04 UTC, mindrones commented on data/processed/patents/total_inventions.csv
> +,year,nuts_id,nuts_year_spec,total_inventions
please remove the index column here

2020-02-20 12:04 UTC, mindrones commented on data/processed/patents/total_inventions.csv
> +0,2013,UKC1,2013,157
Have you run autonuts here? I'm not sure if `year` being same as `nuts_year_spec` would be correct

2020-02-20 12:04 UTC, mindrones commented on data/processed/patents/total_inventions.yaml
> +api: mySQL
This needs to be update to the newer schema template

2020-02-20 15:17 UTC, Juan-Mateos commented
Changed schema and updated `nuts_year_spec`

2020-02-20 16:11 UTC, mindrones requested changes
still some change required

2020-02-20 16:11 UTC, mindrones commented on data/processed/patents/total_inventions.csv
> +0,2013,UKC1,2013,157
Years now seem correct but we need to fix the first column

2020-02-20 16:11 UTC, mindrones commented on data/processed/patents/total_inventions.yaml
> +# [1] https://docs.python.org/3/library/string.html#format-specification-mini-language
minor, I'd remove these 2 lines

2020-02-21 13:02 UTC, mindrones approved these changes
Good to merge once addressed the suggested changes

2020-02-21 13:02 UTC, mindrones commented on data/processed/patents/total_inventions.yaml
> +    type: GeoRegion.nuts_id
This should be `NutsRegion.nuts_id`

2020-02-21 13:02 UTC, mindrones commented on data/processed/patents/total_inventions.yaml
> +    type: GeoRegion.nuts_year_spec
THis should be `type: NutsRegion.nuts_year_spec`

2020-02-21 13:02 UTC, mindrones commented on data/processed/patents/total_inventions.yaml
> +# [1] https://docs.python.org/3/library/string.html#format-specification-mini-language
minor, but these are still in

2020-02-21 13:33 UTC, Juan-Mateos commented
Fixed schema

2020-02-21 13:44 UTC, mindrones approved these changes
Good to merge.

2020-02-21 14:53 UTC, merged