APS collection changes
nestauk/beis-indicators pull request #177
Opened 2020-03-27 21:18 UTC by dede95

Closes #175
* Collection of APS data based on the NUTS 2 & 3 regions used in observation year
* .yaml files appended and added according to change
* Updated 09_ao_aps_data according to change

2020-04-03 15:02 UTC, mindrones requested changes
Some changes required

2020-04-03 15:02 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +endpoint_url: {
There should be no need for curly braces here (this seems to be repeated so this applies to all similar cases)

2020-04-03 15:02 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts3.csv
> +2018,UKI71,2016,
There seems to be no value on this and in other lines of this file

2020-04-03 15:02 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +  } # nuts_spec_year: endpoint_url
leftover comment? (this seems to be repeated so this applies to all similar cases)

2020-04-03 15:02 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts3.csv
> +2012,UKM50,2010,8500.0
The schema seems to indicate these as `int` so I'd remove the decimal here

2020-04-03 15:02 UTC, mindrones commented on ds/data/processed/aps/aps_nvq4_education_data.nuts3.yaml
> +    format: .1
This should be `format: .1f` (we got it wrong originally, I'm changing these in an upcoming PR)

2020-04-03 15:02 UTC, mindrones commented on ds/data/processed/aps/aps_pro_occupations_data.nuts3.yaml
> +    format: .1
This should be `format: .1f`

2020-04-06 10:24 UTC, dede95 commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +endpoint_url: {
This is what agreed on though. Especially for the APS datasets that have different endpoint URLs for each NUTS 2 codes used.

2020-04-06 10:33 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +endpoint_url: {
Yes we agreed to show an object here but I meant that a yaml object does not need curlies. It should be like this:

```yaml
endpoint_url:
  2010: https://www.nomisweb.co.uk/api/v01/dataset/NM_17_1.jsonstat.json?geography=1908408321...1908408356&date=latestMINUS27,latestMINUS23,latestMINUS19&cell=404882177,404883201&measures=20100,20701,
  2013: https://www.nomisweb.co.uk/api/v01/dataset/NM_17_1.jsonstat.json?geography=1887436801...1887436839&date=latestMINUS15,latestMINUS11,latestMINUS7&cell=404882177,404883201&measures=20100,20701,
  2016: https://www.nomisweb.co.uk/api/v01/dataset/NM_17_1.jsonstat.json?geography=1837105153...1837105192&date=latestMINUS3&cell=404882177,404883201&measures=20100,20701
```

2020-04-06 12:07 UTC, dede95 commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +endpoint_url: {
Ah okay. Will get rid of them 👍.

2020-04-06 13:03 UTC, dede95 commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +  } # nuts_spec_year: endpoint_url
@mindrones Made comment since it's not clear that those are the `nuts_spec_year`

2020-04-06 13:39 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts2.yaml
> +  } # nuts_spec_year: endpoint_url
Ah I see, OK

2020-04-06 13:50 UTC, dede95 commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts3.csv
> +2018,UKI71,2016,
@mindrones Should I drop the rows with no value?

2020-04-06 14:11 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts3.csv
> +2018,UKI71,2016,
OK 👍

2020-04-07 10:16 UTC, mindrones approved these changes
Good to merge after adding `schema.value.id` to all `.nuts3.yaml` files as we discussed, thanks!

2020-04-07 10:16 UTC, mindrones commented on ds/data/processed/aps/aps_econ_active_stem_associate_profs_data.nuts3.yaml
> +    label: Frequency
the `id` field is missing here

2020-04-07 15:36 UTC, merged